New solvent
MRChemSoft/mrchem pull request #242
Opened 2019-10-04 14:08 UTC by Gabrielgerez

Solvent effect that has been brought up to date to the mrchem code. Less commits this time

2019-10-04 14:36 UTC, robertodr commented on src/chemistry/Cavity.cpp
> +    double val;
I think this is unused

2019-10-05 09:02 UTC, robertodr commented on src/qmoperators/two_electron/ReactionPotential.cpp
> +        std::cout << "error:\t" << error << "\n"
Shouldn't `Printer` be used to write to the output file?

2019-10-05 09:05 UTC, robertodr commented on src/qmoperators/two_electron/ReactionPotential.cpp
> +    }
Are you sure you wrote the branching correctly here? It seems to me the `else if` is redundant?

2019-10-05 09:11 UTC, robertodr commented on src/qmoperators/two_electron/ReactionPotential.cpp
> +    V_tot_func.alloc(NUMBER::Real);
It's probably a good idea to have a `reset` method to abstract this pattern away and avoid boilerplate code.

2019-10-05 09:14 UTC, robertodr commented on src/qmoperators/two_electron/ReactionPotential.cpp
> +void ReactionPotential::setup(double prec) {
Is this method only called once when initialising the object? If yes, I think some of the code later on is redundant. If not, then the name of the method is a bit confusing.

2019-10-05 09:15 UTC, robertodr commented on src/qmoperators/two_electron/ReactionPotential.cpp
> +    if (not temp.hasReal()) {
See my initial comment on this method. If this is guaranteed to only be called once, then I don't see why the conditional with two branches is needed.

2019-10-08 08:06 UTC, Gabrielgerez commented on src/chemistry/Cavity.cpp
> +    double val;
I think so too

2019-10-08 08:33 UTC, Gabrielgerez commented on src/chemistry/Cavity.cpp
> +}
No longer needed and thus removed. Everything is done in the parser level.

2019-10-08 08:37 UTC, Gabrielgerez commented on src/chemistry/Molecule.cpp
> +    if (cavity != nullptr) MSG_ABORT("Cavity already initialized");
so i can replace `(cavity != nullptr)` with  `(cavity)` and it will still give the same check?

2019-10-08 09:48 UTC, robertodr commented on src/chemistry/Molecule.cpp
> +    if (cavity != nullptr) MSG_ABORT("Cavity already initialized");
Yes: https://coliru.stacked-crooked.com/a/2ea2d3788ceac058

2019-10-09 12:29 UTC, Gabrielgerez commented on src/qmoperators/two_electron/ReactionPotential.cpp
> +    if (not temp.hasReal()) {
It is called on the first SCF iteration, but not every time a new `ReactionOperator` instance is created.
I run this 0th iteration once to create a potential which is carried on to the next SCF cycle. 
From what i gather a new `ReactionOperator` instance is created each SCF iteration, and i don't want to do a new 0th iteration everytime, so i just have a test to see if there already has been a SCF iteration before.

2019-10-09 12:30 UTC, Gabrielgerez commented on src/chemistry/Cavity.cpp
> +    double stdDeviation = d;
Using d directly now

2019-10-09 12:31 UTC, Gabrielgerez commented on src/chemistry/Cavity.cpp
> +#include "MRCPP/Printer" //testing only, remove when done
was it `<vector>` that was unused?

2019-10-10 09:57 UTC, stigrj commented on src/qmoperators/two_electron/ReactionPotential.cpp
> +void ReactionPotential::setup(double prec) {
All QM operators come with a pair of functions `setup(double prec)` and `clear()`. The `setup` will prepare the operator for application and the `clear` will undo. General workflow
```
QMOperator O;              // initialize operator with necessary parameters
for (each SCF cycle) {
    O.setup(current_prec); // prepare operator, e.g. compute potential V
    Orbital psi = O(phi);  // apply operator, e.g. multiply potential V*phi
    O.clear();             // undo the setup, e.g. delete potential V
}
```
This operator is a bit special since the first `setup` is different from later `setup`s.

2019-10-10 09:59 UTC, stigrj commented on src/qmoperators/two_electron/ReactionPotential.cpp
> +    if (not temp.hasReal()) {
There should be created only one `ReactionOperator` at the start of the calculation, but then the underlying potential should be re-computed at every iteration in the `setup`

2019-10-10 10:57 UTC, stigrj commented on src/chemistry/Cavity.cpp
> +bool Cavity::isZeroOnInterval(const double *a, const double *b) const {
Yes, it should ideally be `std::array` but this is a virtual `override` from mrcpp so it has to be changed there first.

2019-10-10 10:59 UTC, stigrj commented on src/chemistry/Cavity.h
> +    bool isZeroOnInterval(const double *a, const double *b) const;
You should add a `override` to these functions

2019-10-10 11:03 UTC, stigrj commented on src/chemistry/Cavity.cpp
>      double s, O;
You should rather declare `s` and `O` inside the loop to limit their scope

2019-10-10 11:05 UTC, stigrj commented on src/chemistry/Cavity.h
>  #include <vector>
Do you need all these includes? Try to remove or move to .cpp file

2019-10-10 11:10 UTC, stigrj commented on src/chemistry/Cavity.h
> +    void changeRadius(double r) { this->R[0] = r; }
This will only change the first entry?

2019-10-10 12:17 UTC, stigrj commented on src/scf_solver/OrbitalOptimizer.cpp
> +            F.getReactionOperator()->setGammanp1(gammanp1);
We need to find a more elegant solution for this

2019-10-11 09:11 UTC, Gabrielgerez commented on src/chemistry/Cavity.cpp
> +#include "MRCPP/Printer" //testing only, remove when done
I think i have removed all the unused headers

2019-10-11 09:11 UTC, Gabrielgerez commented on src/chemistry/Cavity.cpp
>      double s, O;
Done!

2019-10-11 09:14 UTC, Gabrielgerez commented on src/chemistry/Molecule.cpp
> +    if (cavity != nullptr) MSG_ABORT("Cavity already initialized");
ok

2020-02-17 08:26 UTC, Gabrielgerez commented on src/qmoperators/two_electron/ReactionPotential.cpp
> +    V_tot_func.alloc(NUMBER::Real);
Added it in the newest commit

2020-02-17 08:28 UTC, Gabrielgerez commented on src/scf_solver/OrbitalOptimizer.cpp
> +            F.getReactionOperator()->setGammanp1(gammanp1);
agree, @robertodr adviced to do the substraction in the potential, which is included in the latest commit, we still need to add it to the vector and back to the potential, as of now.

2020-04-24 09:51 UTC, robertodr commented
@Gabrielgerez you might want to rebase on top of #293 once it's in, to fix the error from the bot.

2020-04-25 15:04 UTC, robertodr commented on src/qmfunctions/orbital_utils.cpp
> +
Remove this space.

2020-04-28 08:00 UTC, Gabrielgerez commented on src/chemistry/Cavity.cpp
> +                }
If i did not do that then the function would go towards infinity when the denominator was small enough. this at least seems to set a limit. I'm not so sure of its safety though

2020-04-28 10:09 UTC, Gabrielgerez commented on src/qmoperators/two_electron/ReactionOperator.h
> +    QMFunction &getPotential() { return *this->potential; }
If I remember correctly it was required by other methods in `FockOperator.cpp` and `Driver.cpp` at the time they were created. @stigrj is there a reason for this?

2020-04-30 16:07 UTC, robertodr commented on src/qmoperators/two_electron/ReactionPotential.cpp
> +                                      double *error) {
Why pass by pointer? Can you instead `return error;`?

2020-04-30 16:10 UTC, robertodr commented on src/qmoperators/two_electron/ReactionPotential.h
> +    double &getElectronIn();
Return by value, not by reference. And mark as `const`.

2020-04-30 16:10 UTC, robertodr commented on src/qmoperators/two_electron/ReactionPotential.h
> +    bool &getRunVariational() { return variational; }
Return by value and mark as `const`.

2020-04-30 16:18 UTC, robertodr commented on src/qmoperators/two_electron/ReactionPotential.h
> +    bool is_lin;      // determines if the dielectric function will be implemented linearly or exponentially
I suggest you implement a permittivity profile class to make this part more general and more easily extended in the future.

2020-04-30 16:20 UTC, robertodr commented on src/qmoperators/two_electron/ReactionPotential.h
> +    bool variational; // determines if the Reaction potential will be optimized in its own loop each SCF iteration or if
The solver, variational or iterative, can be abstracted into two separate classes that perform the variational step or the microiterations. This is probably more generality than we need, but worth a thought.

2020-04-30 16:44 UTC, robertodr commented on src/scf_solver/GroundStateSolver.cpp
> +            F.getReactionOperator()->setDiffFunc(diff_func);
This looks rather contrived and will surely come back at us with a vengeance. 
What this does (correct me if wrong):
1. Push the potential at the current iterate for`V_r` and the difference with the previous iterate `diff_func` in the global KAIN history, which includes the orbitals.
2. Extrapolate.
3. Set extrapolated `V_r` and `diff_func` into the `ReactionOperator` object instance.
4. Pop them out off the global KAIN history.

Where is the KAIN history for the reaction potential?

2020-05-01 07:22 UTC, stigrj commented on src/input/template.yml
> +        default: 2.0
But then the user has to set it, regardless if it's used or not?

2020-05-01 07:25 UTC, stigrj commented on src/input/template.yml
> +          Coordinates and radii in xyz format.
Again, without a default every user will have to set this

2020-05-01 07:43 UTC, stigrj commented on src/input/template.yml
> +      - name: reaction_energy
This is currently used to trigger the addition of the `ReactionPotential` to the `FockOperator`, right? So this should be moved either to the `Environment` section as a keyword that says "use this environment", or perhaps to the `WaveFunction` section
```
WaveFunction {
  method = HartreeFock
  environment = pcm          # or solvent = true or whatever
  external_field = electric  # <- this is currently not in this section, but
}                            # could be more appropriate to add here as well
```

2020-05-01 07:47 UTC, stigrj commented on src/driver.cpp
> +    auto width = json_mol["cav_width"].get<double>();
Use full name `cavity_width`

2020-05-01 08:34 UTC, robertodr commented on src/input/template.yml
> +        default: 2.0
True that...

2020-05-06 12:15 UTC, Gabrielgerez commented on src/input/template.yml
> +          Run a variational computation of the reaction field energy.
This is done now

2020-05-06 12:18 UTC, Gabrielgerez commented on src/input/template.yml
> +  - name: SolventEffect
its done

2020-05-06 12:19 UTC, Gabrielgerez commented on src/input/template.yml
> +          History for convergence accelerator
added this to the latest commit

2020-05-06 12:21 UTC, Gabrielgerez commented on src/qmoperators/two_electron/ReactionOperator.h
> +    QMFunction &getPotential() { return *this->potential; }
seems like it wasn't needed anyways, at least for now. All of the return by reference methods here have been changed.

2020-09-09 07:18 UTC, Gabrielgerez commented
Have now separated the nested procedure from the variational procedure. 
TODO:
- Rearrange Cavity.cpp
- Set tests for solvent

2020-09-09 08:56 UTC, Gabrielgerez commented on src/chemistry/Cavity.cpp
> +    for (int j = 0; j < 3; j++) {
wouldn't the loop at the end just not run?
`this->gradvector` has size 0 at the start of the loop. The size of the vector should be 3 when it is finished, as it is a 3D gradient of a scalar function with three arguments.

2020-11-13 11:56 UTC, stigrj requested changes
Can you remove _all_ changes in the `pilot` directory?

I think we should modularize and move the following files to a new `solvent` or `environment` directory, i.e. leave only the `ReactionPotential`:
- SCRF
- Permittivity
- Cavity

Opinion on the name @robertodr? `environment` is more general, but can be confused with build environment, and we already have a `mrenv` file which initializes the MR world. 

We also need to think carefully about the input parameters before this is officially released, but that can wait for now.

2020-11-13 11:56 UTC, stigrj commented on external/upstream/fetch_mrcpp.cmake
> +  #set(CMAKE_BUILD_TYPE Release)
Why commented? I guess it doesn't matter since `Release` is default, but still

2020-11-13 11:56 UTC, stigrj commented on src/qmoperators/two_electron/ReactionPotential.h
> +using OrbitalVector_p = std::shared_ptr<mrchem::OrbitalVector>;
Please don't use this in headers

2020-11-13 11:56 UTC, stigrj commented on src/qmoperators/two_electron/SCRF.h
> +using OrbitalVector_p = std::shared_ptr<mrchem::OrbitalVector>;
remove from header

2020-11-13 11:57 UTC, stigrj commented
Looks like the MPI build fails. I will try to debug

2020-11-13 12:24 UTC, robertodr commented on external/upstream/fetch_mrcpp.cmake
> +  #set(CMAKE_BUILD_TYPE Release)
This might have been I suggestion I made to run the debugger and get sensible backtraces.

2020-11-13 12:25 UTC, robertodr commented
I agree with reorganizing files. As for the name of the new folder, I prefer `environment`.

2020-11-13 13:13 UTC, stigrj commented
I can't find any MPI errors locally, so probably just a CircleCI glitch

2020-11-13 14:36 UTC, stigrj commented
@robertodr can you tell what's wrong with Minazo? Looks like it can't find the PR branch

2020-11-13 14:56 UTC, robertodr commented
> @robertodr can you tell what's wrong with Minazo? Looks like it can't find the PR branch

I don't know what's wrong, it could be a problem with the secret token. Please disregard it for the moment being.

2020-11-18 09:06 UTC, robertodr requested changes
Some more changes needed before this goes in.

When including header files follow this order:
1. Headers from the standard library, *i.e.* `#include <string>`
2. Headers from external libraries, *i.e.* `#include <Eigen/Dense>` (or MRCPP or nlhomann_json or XCFun)
3. Headers from the current project, *i.e.* `#include "chemistry/Nucleus.h"`
4. Headers from the current folder, *i.e.* `#include "FockOperator.h"` (if in `qmoperators/two_electron` for example)

The only exception to this ordering is in the implementation file of a class. Then the corresponding header **must** come first.

Another point to consider in header files is to forward-declarer whenever possible, to reduce compilation times. See here for a guide: https://pcmsolver.readthedocs.io/en/latest/programmers/coding-standards.html#including-header-files

2020-11-18 09:06 UTC, robertodr commented on src/scf_solver/KAIN.cpp
> +        A_matrices.push_back(orbA * alpha);
Are we using this at all for the reaction potential? If yes, is there a way to set the scaling parameter from the input?

2020-11-18 10:09 UTC, stigrj commented on pilot/mrchem.cpp
> +#include "MRCPP/MWOperators"
All the `pilot/` commits should be removed from this PR

2020-11-24 12:09 UTC, Gabrielgerez commented on external/upstream/fetch_mrcpp.cmake
> +  #set(CMAKE_BUILD_TYPE Release)
ok

2020-11-26 12:05 UTC, Gabrielgerez commented on src/qmoperators/two_electron/ReactionPotential.h
> +using OrbitalVector_p = std::shared_ptr<mrchem::OrbitalVector>;
do you mean the alias or the includes?

2020-11-26 12:40 UTC, robertodr commented on src/qmoperators/two_electron/ReactionPotential.h
> +using OrbitalVector_p = std::shared_ptr<mrchem::OrbitalVector>;
The alias. It will be visible in any other files that does `#include "ReactionPotential.h"` You can put it in the `public` part of the class and you wouldn't need to modify the cpp file (I think!)

2020-11-26 14:21 UTC, Gabrielgerez commented on python/template.yml
> +          Extrapolate on the reaction potential if true, or on the surface charge distribution in the convergence acceleration.
yes, but i'm not sure what result that would give

2020-11-26 14:48 UTC, Gabrielgerez commented on python/template.yml
> +              Run linear formulation of the Permittivity function, false runs exponential.
The linear option is deprecated, I'll remove this option as the only one used now is exponential. 
Alternatively, I could keep this and modify it to a string with only exponential available, in case of future development

2020-11-26 14:51 UTC, robertodr commented on python/template.yml
> +          Extrapolate on the reaction potential if true, or on the surface charge distribution in the convergence acceleration.
Then it's maybe best to remove the option completely.

2020-11-26 14:59 UTC, robertodr commented on python/template.yml
> +              Run linear formulation of the Permittivity function, false runs exponential.
Let's do the string thing, for future-proofing.

2020-11-26 15:44 UTC, Gabrielgerez commented on pilot/mrchem.cpp
> +#include "chemistry/Permittivity.h"
most of them weren't needed

2020-11-29 09:39 UTC, stigrj commented
The `ReactionOperator` and `ReactionPotential` should still be in `qmoperators` :slightly_smiling_face: The `environment` should contain everything needed to produce the `ReactionPotential`: `Cavity`, `Permittivity` and `SCRF` for now

2020-12-10 08:48 UTC, Gabrielgerez commented on python/template.yml
> +            default: 2.0
It seems a bit of bugs appeared when removing the default for the permittivity outside the cavity, which i found hard to solve. It is back in now :/
I agree as well that it would be better to not have a default

2020-12-10 08:49 UTC, Gabrielgerez commented on python/template.yml
> +              Run linear formulation of the Permittivity function, false runs exponential.
done

2020-12-10 08:51 UTC, Gabrielgerez commented on pilot/mrchem.cpp
> +#include "MRCPP/MWOperators"
I think all of them are gone now, and I have changed all external libraries as Roberto suggested

2020-12-10 08:51 UTC, Gabrielgerez commented on pilot/mrchem.cpp
they weren't needed, they are gone now :)

2020-12-10 09:08 UTC, Gabrielgerez commented on src/chemistry/Permittivity.h
> +    /** @brief Changes the value of #inverse. */
which function? the constructor, evalf or flipFunction?

2020-12-10 09:09 UTC, Gabrielgerez commented on src/scf_solver/KAIN.cpp
> +        A_matrices.push_back(orbA * alpha);
We are not using it on the internal loop.

2020-12-10 10:12 UTC, Gabrielgerez commented on src/chemistry/Cavity.cpp
> + * sphere in the cavity, and \f$\operatorname{s}\f$ is the signed normal distance from the surface of each sphere.
Is it better now?

2020-12-10 13:25 UTC, robertodr commented on python/template.yml
> +            default: 2.0
Can you show what happens when you remove the default? This should be fixed properly.

2020-12-10 13:26 UTC, robertodr commented on src/scf_solver/KAIN.cpp
> +        A_matrices.push_back(orbA * alpha);
If it's not used, should it then be removed completely? It makes the code harder to understand.

2020-12-10 13:30 UTC, robertodr commented on python/mrchem/api.py
> +                    print("Invalid coordinate: " +  " " + str(center))
Use an f-string here: `print(f"Invalid coordinate {center}")

2020-12-10 13:34 UTC, robertodr commented on python/template.yml
> +            - "value.lower() in ['scrf', 'variational']"
Should `'variational'` be here?

2020-12-10 13:39 UTC, robertodr commented on src/chemistry/chemistry_utils.h
> +Density compute_nuclear_density(double prec, const Nuclei &nucs, double alpha);
This function is still undocumented

2020-12-10 13:46 UTC, Gabrielgerez commented on python/template.yml
> +            - "value.lower() in ['scrf', 'variational']"
It shouldn't be there

2020-12-10 13:54 UTC, robertodr commented on src/environment/Permittivity.h
> +    bool inverse = false;    //!< State of #evalf
I'm being really dense, but can you explain what `inverse` is supposed to achieve? I'm a bit worried of this kind of stateful object...

2020-12-10 13:56 UTC, robertodr reviewed
I've left some more comments. We're really close to merging this :smile_cat: Did you try running a test with a classical charge only that @ilfreddy suggested?

2020-12-10 13:59 UTC, Gabrielgerez commented on src/environment/Permittivity.h
> +    bool inverse = false;    //!< State of #evalf
if `false` evalf returns epsilon(r)
if `true` evalf returns 1/epsilon(r)

2020-12-10 14:01 UTC, Gabrielgerez commented on src/environment/Permittivity.h
> +    bool inverse = false;    //!< State of #evalf
@stigrj mentioned once that I could avoid this by using a map method, but i'm not sure how it was implemented

2020-12-10 14:06 UTC, Gabrielgerez commented
Not yet. I had actually forgotten about that suggestion :sweat_smile: I can include some options to the code for this types of test

2020-12-10 14:38 UTC, Gabrielgerez commented on src/chemistry/Permittivity.h
> +    /** @brief Changes the value of #inverse. */
I've put a more extended explanation of the function now

2021-01-22 10:58 UTC, stigrj commented
Ok, it's about time to get this one in. Some of this will likely change a bit in the future, but I think we should just merge it. One last question: how do you scale the vdW radius? Shouldn't there be a simplified input for this, if you want to use vdW spheres, but with scaled radius?

2021-01-22 12:12 UTC, Gabrielgerez commented
> Ok, it's about time to get this one in. Some of this will likely change a bit in the future, but I think we should just merge it. One last question: how do you scale the vdW radius? Shouldn't there be a simplified input for this, if you want to use vdW spheres, but with scaled radius?

The cavity coordinates are either explicitly given (both position and radius size) by the user, or are constructed from the atomic coordinates with the vdw-radii from the periodic table.
the scaling happens per sphere radius, that is, multiply each radius by the scaling factor. This is done by the user beforehand.
There is no scaling factor in the code yet, but I think it might be a good idea to add a scaling parameter in the input, although it might increase confusion in the event of both cavity coordinates and scaling factor given.

2021-01-25 10:00 UTC, Gabrielgerez commented
@stigrj @robertodr What do you guys think, should we merge it as it is?

2021-01-25 10:03 UTC, stigrj approved these changes

2021-01-25 10:03 UTC, stigrj commented
Sorry, got distracted on friday and forgot about it :slightly_smiling_face:

2021-01-25 10:20 UTC, stigrj commented
Needs approval by @robertodr as well, it seems

2021-01-25 11:46 UTC, robertodr approved these changes
Very good!

2021-01-25 11:46 UTC, merged