Separate molecule sanity checks from the writing of program input
MRChemSoft/mrchem pull request #404
Opened 2022-03-25 09:06 UTC by Andersmb

In trying to grasp the flow of the input parser, I thought it could improve readability and understanding by separating the sanity checks performed on the molecule input section from the actual writing of program syntax in `python/mrchem/api.py`. 

Now all the checks are performed in `python/mrchem/validators.py` by `MoleculeValidator`, along with a couple of new ones. 

Atomic coordinates
- Correct XYZ format checked with regexes (both atomic symbols 
  and numbers are valid atom identifiers, and can be used 
  interchancably in the same input)
- Nuclear singularities
- Atomic symbols checked against periodic table 

Cavity spheres
- Correct format checked with regexes
- Negative radii not allowed

Electrons, charge and multiplicity
- charge > Z not allowed
- n_unpaired > n_electrons not allowed
- multiplicity and n_electrons both odd/even not allowed
- restricted open-shell not allowed

Unit conversions
- convert to bohr if user specified angstrom

Translate CoM
- if requested, translate CoM to the origin

The last two are not really sanity checks, and would perhaps better belong back in `api.py`?

**The only problem is that the `li_solv` test fails for some reason. Test output:**

```console
30: running /Users/abr121/Developments/MRChem/mrchem/build_manual/bin/mrchem /Users/abr121/Developments/MRChem/mrchem/tests/li_solv/li --executable=/Users/abr121/Developments/MRChem/mrchem/build_manual/bin/mrchem.x
30: test with input files /Users/abr121/Developments/MRChem/mrchem/tests/li_solv/li and args None
30: 
30:     JSON['output']['properties']['orbital_energies']['sum_occupied']: computed value (-4.42131901) does not match (-4.43777713) to atol=1e-06, rtol=1e-06 by difference (0.01645812).
30:     JSON['output']['properties']['scf_energy']['E_kin']: computed value (7.58421212) does not match (7.57152585) to atol=1e-06, rtol=1e-06 by difference (0.01268626).
30:     JSON['output']['properties']['scf_energy']['E_en']: computed value (-16.49147605) does not match (-16.47750955) to atol=1e-06, rtol=1e-06 by difference (-0.01396650).
30:     JSON['output']['properties']['scf_energy']['E_ee']: computed value (3.35767887) does not match (3.35462583) to atol=1e-06, rtol=1e-06 by difference (0.00305305).
30:     JSON['output']['properties']['scf_energy']['E_x']: computed value (-0.41959415) does not match (-0.41920404) to atol=1e-06, rtol=1e-06 by difference (-0.00039011).
30:     JSON['output']['properties']['scf_energy']['E_xc']: computed value (-1.28684906) does not match (-1.28574001) to atol=1e-06, rtol=1e-06 by difference (-0.00110906).
30:     JSON['output']['properties']['scf_energy']['E_eext']....................................................................PASSED
30:     JSON['output']['properties']['scf_energy']['E_next']....................................................................PASSED
30:     JSON['output']['properties']['scf_energy']['E_el']: computed value (-7.12794693) does not match (-7.13513552) to atol=1e-06, rtol=1e-06 by difference (0.00718859).
30:     JSON['output']['properties']['scf_energy']['Er_tot']: computed value (-0.06404740) does not match (-0.06057296) to atol=1e-06, rtol=1e-06 by difference (-0.00347444).
30:     JSON['output']['properties']['scf_energy']['Er_el']: computed value (0.12808134) does not match (0.12116639) to atol=1e-06, rtol=1e-06 by difference (0.00691494).
30:     JSON['output']['properties']['scf_energy']['Er_nuc']: computed value (-0.19212873) does not match (-0.18173935) to atol=1e-06, rtol=1e-06 by difference (-0.01038938).
29/31 Test #30: Li_solvent_effect ................***Failed   69.46 sec
```

Perhaps @Gabrielgerez could take a look and see if something is weird in `self.validate_cavity()`?

2022-03-25 09:55 UTC, stigrj commented
I believe this file [python/mrchem/input_parser/plumbing/__init__.py](https://github.com/MRChemSoft/mrchem/pull/404/files#diff-e7dbd0887ae4697a86c6b069f02dc856d381b1709140ce33b87110262e7675eb) should not be committed. It was the one causing problems before (reason still unknown). Are you now able to run with file in source?

2022-03-25 10:07 UTC, Andersmb commented
Ah, that one slipped through. Very annoying. Why has this file started causing problems?

Another thing. The `ANG_2_BOHR` conversion factor is present both in `helpers.py` and `CUBEparser.py`. The cube parser cannot import from helpers due to circular import errors. A simple fix solution could be to collect the constants we use during input parsing in its own file, and import from there. Perhaps ideally python and c++ should access the same set of constants (this is perhaps what you mentioned in #171)

2022-03-25 10:13 UTC, Gabrielgerez commented
That li_solv has always had weird behavior, I'll check it out

2022-03-25 10:13 UTC, stigrj commented
@robertodr do you know why this file suddenly started to appear?

I think one nice way to handle the constants is to let Python define them and feed them into the C++ program through the JSON input. Then we also have complete control and can tweak the parameters without recompiling, by intercepting the input parser and edit the JSON file before execution.

2022-03-25 10:16 UTC, robertodr commented
@Andersmb Which version of `pyparsing` is installed locally? `parselglossy` cannot yet deal with v3 of that library, I think that's what you're seeing. I opened a PR sometime ago to fix that https://github.com/dev-cafe/parselglossy/pull/109 Didn't get around to finishing it.

2022-03-25 10:17 UTC, robertodr commented
The quick solution is to ignore any change in that `plumbing` when committing.

2022-03-25 10:18 UTC, Andersmb commented
> The quick solution is to ignore any change in that `plumbing` when committing.

I have version `3.0.7` installed...

2022-03-25 10:22 UTC, robertodr commented
> > The quick solution is to ignore any change in that `plumbing` when committing.
> 
> I have version `3.0.7` installed...

Mystery understood then.

2022-03-25 10:51 UTC, Andersmb commented
> @robertodr do you know why this file suddenly started to appear?
> 
> I think one nice way to handle the constants is to let Python define them and feed them into the C++ program through the JSON input. Then we also have complete control and can tweak the parameters without recompiling, by intercepting the input parser and edit the JSON file before execution.

Should we base it on some official set of constants, as `QCElemental` does with the nist files? The nist data files was over 2000 lines, so it contains a lot of stuff we don't need, but gave a lot of neat stuff like descriptions, units, etc. And they don't come with intuitive names, so to actually access common constants we would perhaps need to manually define some type of aliases... I think that is what is done in `QCElemental`...?

Or simply make a python class that holds the set of constants currently present in `mrchem.h`, and define them explicitly, and update this whenever a new constant is needed?

aka
```python
class PhysConstants:
         kJ        = 2625.49962;         // AU -> kJ/mol conversion factor
         kcal      =  627.509469;        // AU -> kcal/mol conversion factor
         eV        =   27.21138505;      // AU -> eV conversion factor
         JT_m2     =   78.9451185;       // AU -> 10^(-30) J/T^2 (SI magnetizability)
         Debye     =    2.54174623105;   // AU -> Debye conversion factor
         cm_m1     =    1.0e7 / 45.5640; // AU -> cm^(-1) frequency -> wavelenght
         alpha     =    7.2973525664;    // Fine structure constant
         g_e       =    2.0023193043618; // Free-electron g-value
         beta_e    =    0.5000000;       // Bohr magneton
         beta_N    =    0.0002723;       // Nuclear magneton
         alpha_inv =  137.035999084;     // Inverse of the fine structure constant alpha
```
(perhaps with more intuitive names and units added in)

Or it should be easy parse the nist file for values and units, and set up a class like above but only with some set of predefined constants that we need..

2022-03-28 12:03 UTC, Andersmb commented
@Gabrielgerez I discovered why the `li_solv` was failing. The `Molecule.cavity_coords` section had a duplicated sphere

```json
"cavity_coords": [
        {
          "center": [
            0.0,
            0.0,
            0.0
          ],
          "radius": 4.0
        },
        {
          "center": [
            0.0,
            0.0,
            0.0
          ],
          "radius": 4.0
        }
      ]
```

Just deleting the extra sphere lead to a passing test.

2022-03-31 16:06 UTC, Andersmb commented
@stigrj Many unit tests will now fail because they are not being fed the constants generated by the input parser. How best solve this?

2022-03-31 17:11 UTC, stigrj commented
Hmm yes, we probably need some defaults on the C++ side. Did you get around the linking issue?

2022-04-01 07:28 UTC, robertodr commented
As for the singleton, I would use the pattern given in Alexandrescu's "Modern C++ Design" which uses static local references and avoids spilling around pointers and checking for `NULL`s.

`PhysicalConstants.h`
```c++
namespace mrchem {
class PhysicalConstants final {
  public:
     static PhysicalConstants& getInstance(const nlhomann::json & constants = /* */);
     static auto get(const std::string& key) const {
         return constants_[key];
     }
     PhysicalConstants() = default;
   ~PhysicalConstants() = default;
   PhysicalConstants(const PhysicalConstants&) = delete; 
   PhysicalConstants& operator=(const PhysicalConstants&) = delete;
   PhysicalConstants(PhysicalConstants&&) = delete; 
   PhysicalConstants& operator=(PhysicalConstants&&) = delete;
  private:
     PhysicalConstants(const nlhomann::json & constants) : constants_{constants} {}
     nlohmann::json constants_;
};
}
```

`PhysicalConstants.cpp`
```c++
namespace mrchem {
PhysicalConstants& PhysicalConstants::getInstance(const nlhomann::json & constants)
{
	static PhysicalConstants obj(constants);
	return obj;
}
}
```

The default value for the constants can be declared in an anonymous namespace, I think.

2022-04-01 15:20 UTC, Andersmb commented
@robertodr I will update singleton design.

The tests should pass now, but I am not sure if it is the best design. Now some constants are explicitly set in the singleton constructor. I added a method to `MRChemConstants.py` for printing a predefined subset of constants, to help avoid errors (you just need to copy/paste the output into the c++ file).

2022-04-03 12:27 UTC, Andersmb commented
@robertodr I am not able to get this to work. After sorting out a few typos, I end up with `Undefined symbols for architecture x86_64:` errors during compilation, ala:
```console
Undefined symbols for architecture x86_64:
  "mrchem::PhysicalConstants::constants_", referenced from:
      mrchem::driver::build_fock_operator(nlohmann::basic_json<std::__1::map, std::__1::vector, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, bool, long long, unsigned long long, double, std::__1::allocator, nlohmann::adl_serializer> const&, mrchem::Molecule&, mrchem::FockBuilder&, int) in driver.cpp.o
      mrchem::H_M_pso::H_M_pso(mrchem::MomentumOperator, mrchem::NuclearGradientOperator) in driver.cpp.o
      mrchem::H_MB_dia::H_MB_dia(mrchem::PositionOperator, mrchem::NuclearGradientOperator) in driver.cpp.o
      mrchem::H_BM_dia::H_BM_dia(mrchem::PositionOperator, mrchem::NuclearGradientOperator) in driver.cpp.o
      mrchem::AngularFunction::calcConstant() const in HydrogenFunction.cpp.o
      mrchem::chemistry::compute_nuclear_density(double, mrchem::Nuclei const&, double) in chemistry_utils.cpp.o
      mrchem::SCFEnergy::print(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const in Molecule.cpp.o
      ...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I currently have in `PhysicalConstants.h`

```c++
#pragma once
#include <nlohmann/json.hpp>

namespace mrchem {
class PhysicalConstants final {
  public:
     static PhysicalConstants& getInstance(const nlohmann::json &constants);
     static double get(const std::string& key) {
         return constants_[key];
     }
     PhysicalConstants() = default;
   ~PhysicalConstants() = default;
   PhysicalConstants(const PhysicalConstants&) = delete; 
   PhysicalConstants& operator=(const PhysicalConstants&) = delete;
   PhysicalConstants(PhysicalConstants&&) = delete; 
   PhysicalConstants& operator=(PhysicalConstants&&) = delete;

  private:
     PhysicalConstants(const nlohmann::json & constants) { constants_ = constants; }
     static nlohmann::json constants_;
};
}
```

and in `PhysicalConstants.cpp`

```c++
#include "PhysicalConstants.h"
#include <nlohmann/json.hpp>

namespace mrchem {
PhysicalConstants& PhysicalConstants::getInstance(const nlohmann::json & constants) {
	static PhysicalConstants obj(constants);
	return obj;
}
}
```

I think it is means that the private static member `constants_` is declared but not defined anywhere. Perhaps I broke the class when trying to get rid of the compiler errors after copy/pasting...

2022-04-03 17:56 UTC, stigrj commented
I guess this is not in the latest commit you pushed, because that one work fine for me?

Two comments:
- The `constants` input section turned out a bit massive. Can we limit to include only the constants we need?
- The `light_speed` parameter in the ZORA operators should perhaps be moved into this section? But then how should we treat constants that are derived from others in case we want to change the default? One example would be `light_speed` vs `fine_structure_constant`: if we change the speed of light in a ZORA calculation, should we then change the fine-structure constant accordingly in e.g. the NMR operators?

2022-04-04 08:25 UTC, Andersmb commented
@stigrj I updated the python side  so that only the constants we need are added to the program input. The "constants" section now looks like this:

```
"constants": {
      "angstrom2bohrs": 1.8897261246257702,
      "atomic_unit_of_bohr_magneton": 0.5000000000000764,
      "atomic_unit_of_nuclear_magneton": 0.0002723085107443953,
      "c_au": 137.035999084,
      "dipmom_au2debye": 2.5417464739297717,
      "electron_g_factor": -2.00231930436256,
      "fine_structure_constant": 0.0072973525693,
      "hartree2ev": 27.211386245988,
      "hartree2kJmol": 2625.4996394798254,
      "hartree2kcalmol": 627.5094740630558,
      "hartree2simagnetizability": 78.9451185,
      "hartree2wavenumbers": 219474.6313632,
      "pi": 3.141592653589793,
      "pi_sqrt": 1.7724538509055159
    }
```

I see no mention in the ORCA manual that changing the light speed in a relativistic calculation affects any other aspect of that code. But I am not sure what makes sense.

2022-04-04 08:30 UTC, Andersmb commented
Also, how do I add `qcelemental` as a python dependency?  As of now, the source of everything needed on the python side (that is not part of the standard library) is explicitly included, right, to avoid having the user install packages themselves? Do we do the same with `qcelemental`?

2022-04-04 08:51 UTC, stigrj commented
To fix the tests on GitHub Actions I think you just have to add `qcelemental` to `.github/mrchem-gha.yml`. For the general user I'm not sure how we want to do this, perhaps it's not too much to ask of the user to install a simple python package? @robertodr ?

2022-04-04 09:09 UTC, robertodr commented
It's not too onerous to install a Python package. Consider though that we removed the dependency on `runtest` to make development work run smoother. `runtest` was used to only run tests and we could rewrite that functionality in pure Python. `qcelemental` might be used to do more than just supply units of measure so it is a slightly different use case. If there's a way to make the dependency optional, you'd make a few developers happier 😄

2022-04-04 09:44 UTC, stigrj commented
We could use `qcelemental` in the same way we use `parselglossy`, e.i. only by developers once in a while to update a JSON file with the parameters we need. Or, it could be used as part of the `parselglossy` workflow of generating the input template, so that default values are fetched directly from `qcelemental` when we run `parselglossy`?

2022-04-04 12:32 UTC, robertodr commented
> We could use `qcelemental` in the same way we use `parselglossy`, e.i. only by developers once in a while to update a JSON file with the parameters we need. Or, it could be used as part of the `parselglossy` workflow of generating the input template, so that default values are fetched directly from `qcelemental` when we run `parselglossy`?

sounds reasonable, yes. As long as you don't dump all constants and conversion factors the JSON shouldn't be too large.

2022-04-05 13:17 UTC, Andersmb commented
@robertodr 

I have updated the singleton class, but I still get problems during linking:

```make
[ 76%] Linking CXX executable ../bin/mrchem-tests
Undefined symbols for architecture x86_64:
  "mrchem::PhysicalConstants::constants_", referenced from:
      mrchem::PhysicalConstants::PhysicalConstants(nlohmann::basic_json<std::__1::map, std::__1::vector, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, bool, long long, unsigned long long, double, std::__1::allocator, nlohmann::adl_serializer> const&) in PhysicalConstants.cpp.o
Undefined symbols for architecture x86_64:
  "mrchem::PhysicalConstants::constants_", referenced from:
      mrchem::PhysicalConstants::PhysicalConstants(nlohmann::basic_json<std::__1::map, std::__1::vector, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, bool, long long, unsigned long long, double, std::__1::allocator, nlohmann::adl_serializer> const&) in PhysicalConstants.cpp.o
ld: symbol(s) not found for architecture x86_64
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [bin/mrchem.x] Error 1
make[2]: *** [bin/mrchem-pilot.x] Error 1
make[1]: *** [src/CMakeFiles/mrchem.x.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [pilot/CMakeFiles/mrchem-pilot.x.dir/all] Error 2
Undefined symbols for architecture x86_64:
  "mrchem::PhysicalConstants::constants_", referenced from:
      mrchem::PhysicalConstants::PhysicalConstants(nlohmann::basic_json<std::__1::map, std::__1::vector, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, bool, long long, unsigned long long, double, std::__1::allocator, nlohmann::adl_serializer> const&) in PhysicalConstants.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [bin/mrchem-tests] Error 1
make[1]: *** [tests/CMakeFiles/mrchem-tests.dir/all] Error 2
make: *** [all] Error 2
```

Do you understand why the linker complains? The updated code has been pushed.

2022-04-06 13:55 UTC, Andersmb commented
The user can now overwrite the constant defaults in the user input, e.g.

```
Constants {
    pi = 3
}
```

The keywords to the new input section are added automatically by `python/mrchem/update_input_parser.py`, which reads the template and build the `Constants` section based on the constants defined in `MRChemPhysConstants`. It also runs parselglossy and syncs the user ref file.

2022-04-07 08:06 UTC, stigrj commented on python/README.md
> +Copy the user reference file to update the documentation:
I guess if we just add a keyword in an input section unrelated to the constants, we can still update the input in the same way as before, by just running `parselglossy` manually like this?

2022-04-07 08:09 UTC, Andersmb commented on python/README.md
> +Copy the user reference file to update the documentation:
Yes, if the constants are unchanged then one can run parselglossy the same way as before.

2022-04-07 08:21 UTC, stigrj commented on doc/users/user_ref.rst
> +    **Default** ``137.035999084``
I think it would be good to add to the docstring exactly what parts of the code will be affected by changing any of these parameters. E.g. changing the light speed will only affect the relativistic Hamiltonians (so any NREL calculation is unaffected), `hartree2simagnetizability` will only change the printed value of the magnetizability property, etc.

2022-04-07 10:57 UTC, Andersmb commented on doc/users/user_ref.rst
> +    **Default** ``137.035999084``
I have updated the way the constants are defined in `MRChemPhysConstants`. It is more verbose, but I think it is easier to add new constants than the way it was before. I attempted to mention affected code for each constant, but you should probably double check.

2022-04-07 11:11 UTC, stigrj commented on doc/users/user_ref.rst
> +    **Default** ``137.035999084``
Excellent! Are we closing in on a finished version?

2022-04-07 11:15 UTC, Andersmb commented on doc/users/user_ref.rst
> +    **Default** ``137.035999084``
Yes, I think so. There are just a few small formatting issues in the user ref, I just noticed:

 - The title includes the quotes: `"User input reference"`
 - I wanted to add multiline docstrings in `Constants` by using the literal `|` character, but it did not work properly. How should I format the string in Python to ensure that it gets converted to the proper yaml literal string format?

This:

```
docstring = f"""|\nConversion factor from Hartree to kcal/mol  (unit: {unit}).
        Affected code: Printed value of energies."""
```

did not work as I had hoped..

2022-04-07 11:31 UTC, stigrj commented on doc/users/user_ref.rst
> +    **Default** ``137.035999084``
Similar discussion here: https://github.com/dev-cafe/parselglossy/pull/52

So line breaks are explicitly replaced with white-spaces to avoid errors in the rendering of the docs?

2022-04-07 11:42 UTC, Andersmb commented on doc/users/user_ref.rst
> +    **Default** ``137.035999084``
Also, for some reason the units are repeated. They occur at the position specified in the string and also at the end of every string...

2022-04-07 11:55 UTC, Andersmb commented on doc/users/user_ref.rst
> +    **Default** ``137.035999084``
I see. I just made the docstrings into normal strings with a `| `in front. From an online ReStructured viewer it looks like they are rendered okay.

2022-04-07 12:36 UTC, Andersmb commented
Still some bugs floating around.

- [ ]

2022-04-07 14:15 UTC, Andersmb commented
Is it expected that the total energy is identical for one calculation with normal `pi` and one with `pi = 1000000.0`?

2022-04-07 14:19 UTC, stigrj commented
That sounds strange. Maybe it's not used? There's also a `pi` in MRCPP, so maybe that is the one that is actually used?

2022-04-07 14:23 UTC, stigrj commented
Come to think of it, maybe `pi` should be fixed and provided by MRCPP? Then we leave only physical constants to MRChem

2022-04-07 14:35 UTC, Andersmb commented
`HelmholtVector::apply` uses pi, but this method is not currently being called during a normal SCF (we do a `H()` instead). 
pi is also referenced in `Cavity.cpp` and `SCRF.cpp`, so it might be relevant there.
And s unit tests fail when drastically changing the value of pi :)

2022-04-07 14:43 UTC, stigrj commented
I see MRCPP's pi is used once in `tests/qmfunctions/orbital_vector.cpp`. Can you just replace all the pi's with `mrcpp::pi` and remove it from MRChem's constants?

2022-04-22 07:56 UTC, stigrj requested changes

2022-04-22 07:56 UTC, stigrj commented on python/template.yml
> +  - name: numerically_exact
I see the indentation has changed in the entire `template.yml` file, is this intentional?

2022-04-22 07:56 UTC, stigrj commented on src/mrchem.cpp
> +    if (json_inp["printer"]["print_constants"]) PhysicalConstants::Print(print_prec);
I'm not sure about the `print_prec` for this output. If you want to print it (`print_constants == true`), then you probably want the exact value that is used? There's also plenty of space on the line here, so I suggest we just fix it to `print_prec = 14` decimal places here.

2022-04-22 07:56 UTC, stigrj commented on src/chemistry/PhysicalConstants.cpp
> +    mrcpp::print::separator(0, '=');
Can you add some more space between this output and the next:
```
mrcpp::print::separator(0, '=', 2);
```

2022-04-22 07:56 UTC, stigrj commented on src/utils/print_utils.cpp
> +    int w1 = w0 * 2 / 10;
This misaligned some of the `:`'s in the output, but with the old value the name `hartree2simagnetizability` becomes too long... Perhaps abbreviate magnetizability?

2022-04-22 07:56 UTC, stigrj commented on python/mrchem/update_input_parser.py
> +from ruamel.yaml import YAML
`ruamel.yaml` not listed in dev-packages

2022-04-25 12:54 UTC, Andersmb commented on python/template.yml
> +  - name: numerically_exact
hmm, this must be an effect of the `yaml->dict->yaml` roundtrip with `ruamel.yaml`. There are some options for setting indentation - I can see if I can reproduce the original indentation scheme.

2022-04-25 13:02 UTC, Andersmb commented on python/template.yml
> +  - name: numerically_exact
I think the following gets the old indentation (source: https://yaml.readthedocs.io/en/latest/detail.html#:~:text=yaml.indent(mapping%3D2%2C%20sequence%3D4%2C%20offset%3D2))

```python
yaml.indent(sequence=4, mapping=2, offset=2)
```

Excerpt:

```yaml
keywords:
  - name: world_prec
    type: float
    predicates:
      - 1.0e-10 < value < 1.0
    docstring: |
      Overall relative precision in the calculation.
  - name: world_size
    type: int
    default: -1
    predicates:
      - value <= 10
    docstring: |
      Total size of computational domain given as 2**(``world_size``). Always cubic
      and symmetric around the origin. Negative value means it will be computed
      from the molecular geometry.
  - name: world_unit
    type: str
    default: bohr
    predicates:
      - value.lower() in ["bohr", "angstrom"]
    docstring: |
      Length unit for *all* coordinates given in user input. Everything will be
      converted to atomic units (bohr) before the main executable is launched,
      so the JSON input is *always* given in bohrs.
  - name: world_origin
    type: List[float]
    default: [0.0, 0.0, 0.0]
    predicates:
      - len(value) == 3
    docstring: |
      Global gauge origin of the calculation.
sections:
  - name: Precisions
    docstring: |
      Define specific precision parameters.
    keywords:
      - name: nuclear_prec
        type: float
        default: user['world_prec']
        predicates:
          - 1.0e-10 < value < 1.0
        docstring: |
          Precision parameter used in smoothing and projection of nuclear potential.
      - name: poisson_prec
        type: float
        default: user['world_prec']
        predicates:
          - 1.0e-10 < value < 1.0
        docstring: |
          Precision parameter used in construction of Poisson operators.
      - name: exchange_prec
        type: float
        default: -1.0
        docstring: |
          Precision parameter used in construction of Exchange operators.
          Negative value means it will follow the dynamic precision in SCF.
      - name: helmholtz_prec
        type: float
        default: -1.0
        docstring: |
          Precision parameter used in construction of Helmholtz operators.
          Negative value means it will follow the dynamic precision in SCF.
```

2022-04-27 08:05 UTC, merged