Print information about the external environments
MRChemSoft/mrchem pull request #408
Opened 2022-04-21 17:54 UTC by Andersmb

In response to #406.

During input parsing, now a short summary label is generated and displayed in the SCF solver table. It indicates whether an implicit solvent is being used, and if a finite external electric is applied. For example, if both are active:

```
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 Calculation             : Optimize ground state orbitals
 Method                  : Hartree-Fock
 Relativity              : None
 Environment             : PCM ; Electric field (0.0, 0.0, 0.01)
 Checkpointing           : Off
 Max iterations          : 5
 KAIN solver             : 3
 Localization            : Off
 Diagonalization         : First two iterations
 Start precision         : 1.00000e-03
 Final precision         : 1.00000e-03
 Helmholtz precision     : Dynamic
 Energy threshold        : Off
 Orbital threshold       : 1.00000e-02
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

A more detailed table is also printed earlier showing some key settings for the implicit solvent. For example:

```
===========================================================================
                      Self-Consistent Reaction Field
---------------------------------------------------------------------------
 Dielectric constant (inside)     :                            1.00000e+00
 Dielectric constant (outside)    :                            2.00000e+00
 Max number of micro-ierations    :                                  100.0
 Accelerate with KAIN             :                                   true
 Algorithm                        :                                   scrf
 Density type                     :                                  total
 Convergence criterion            :                                dynamic
===========================================================================
```

To allow for the rather long names left of the `:`, some tweaks to `print_utils` were needed. A `txtBuffer` option was added that lets a developer give more room if needed (defaults to 0). Also, an option for right-aligning `print_utils::text` was added, but a left-aligned table is perhaps aesthetically more pleasing...?

Should a table similar to the geometry one be printed for the cavity?

2022-04-22 09:58 UTC, stigrj requested changes

2022-04-22 09:58 UTC, stigrj commented on src/environment/SCRF.cpp
> +    print_utils::scalar(0, "Max number of micro-ierations", max_iter, "", 1, false, buffer);
Typo `ierations`. Should be integer output, does it work with `0` decimals?

2022-04-22 09:58 UTC, stigrj commented on src/environment/SCRF.cpp
> +    println(0, "");
This is achieved by adding an extra argument to the `print::separator` call

2022-04-22 09:58 UTC, stigrj commented on src/environment/SCRF.cpp
> +void SCRF::printParameters() {
We might want some information on the actual cavity as well, because I guess we _can_ set up a calculation with just random spheres as cavity, e.i. not restricted to atomic coordinates and vdW radius. Is this right @Gabrielgerez ?

2022-04-22 09:58 UTC, stigrj commented on src/utils/print_utils.cpp
> +    int w1 = w0 * 2 / 9 - txtBuffer;
Not sure how to properly resolve this. We should have something that looks good with the default `print_width` and `print_precision`, but that doesn't crash if we make things too narrow, or when inserting too long strings. So either we truncate the text string to always make it fit, or we always print the full string, even if it becomes unaligned with the rest?

2022-04-25 09:04 UTC, Andersmb commented on src/utils/print_utils.cpp
> +    int w1 = w0 * 2 / 9 - txtBuffer;
As a quick workaround, I thought perhaps of adding a `print_utils::json` method, that takes a json object, determines the longest name of the collection, and adjusts the colon placement accordingly. Could also have an option for right-aligning it. Something like this:

```c++
void print_utils::json(int level, const nlohmann::json &j, bool ralign) {
    // Determine longest name
    int w = 0;
    for (const auto& item : j.items()) {
        if (item.key().size() > w) w = item.key().size();
    }

    // Print
    for (const auto& item : j.items()) {
        std::string key = item.key();
        std::stringstream o_val;
        o_val << item.value();
        std::string val = o_val.str();

        // Remove quotes from val
        val.erase(std::remove(val.begin(), val.end(), '\"'), val.end());

        // If right-align, determine how much to shift the vals
        int shift = (ralign) ? Printer::getWidth() - w - val.size() - 3 : 0;

        std::printf("%-*s%-s%-s%-s\n", w, key.c_str(), " : ", std::string(shift, ' ').c_str(), val.c_str());
    }
}
```

and using it like this

```c++
void SCRF::printParameters() {
    nlohmann::json data = {
        {"Dielectric constant (inside)", epsilon.getEpsIn()},
        {"Dielectric constant (outside)", epsilon.getEpsOut()},
        {"Max. number of micro-iterations", max_iter},
        {"Accelerate with KAIN", (accelerate_Vr) ? "true" : "false"},
        {"Algorithm", algorithm},
        {"Density type", density_type},
        {"Convergence criterion", convergence_criterion},
    };

    mrcpp::print::header(0, "Self-Consistent Reaction Field");
    print_utils::json(0, data, true);
    mrcpp::print::separator(0, '=', 2);
}
```

which produces

```console
===========================================================================
                      Self-Consistent Reaction Field
---------------------------------------------------------------------------
Accelerate with KAIN            :                                      true
Algorithm                       :                                      scrf
Convergence criterion           :                                   dynamic
Density type                    :                                     total
Dielectric constant (inside)    :                                       1.0
Dielectric constant (outside)   :                                       2.0
Max. number of micro-iterations :                                       100
===========================================================================
```

Not sure if the alphabetical order was accidental or not...

2022-04-25 12:36 UTC, Andersmb commented on src/environment/SCRF.cpp
> +void SCRF::printParameters() {
How does this look?

```console
===========================================================================
                             Solvation Cavity
---------------------------------------------------------------------------
 Cavity width            :                                        0.500000
---------------------------------------------------------------------------
    N      Radius        :               x               y               z
---------------------------------------------------------------------------
    0    4.000000        :        0.000000        0.000000        0.000000
    1    4.000000        :        0.000000        0.000000        0.000000
===========================================================================
```

produced from 

```c++
/** @brief Pretty output of solvation cavity spheres */
void Molecule::printCavity() {
    // Collect relevant quantities
    Cavity cavity = getCavity();
    std::vector<mrcpp::Coord<3>> coords = cavity.getCoordinates();
    std::vector<double> radii = cavity.getRadii();

    // Set widths
    auto w0 = Printer::getWidth() - 1;
    auto w1 = 5;
    auto w2 = 12;
    auto w3 = 2 * w0 / 9;
    auto w4 = w0 - w1 - w2 - 3 * w3;

    // Build table column headers
    std::stringstream o_head;
    o_head << std::setw(w1) << "N";
    o_head << std::setw(w2) << "Radius";
    o_head << std::string(w4 - 1, ' ') << ':';
    o_head << std::setw(w3) << "x";
    o_head << std::setw(w3) << "y";
    o_head << std::setw(w3) << "z";

    // Print
    mrcpp::print::header(0, "Solvation Cavity");
    print_utils::scalar(0, "Cavity width", cavity.getWidth(), "", 0);
    mrcpp::print::separator(0, '-');
    println(0, o_head.str());
    mrcpp::print::separator(0, '-');
    for (int i = 0; i < coords.size(); i++) {
        mrcpp::Coord<3> coord = coords[i];
        double r = radii[i];
        double x = coord[0];
        double y = coord[1];
        double z = coord[2];

        std::stringstream o_coord;
        o_coord << std::setw(w1) << i;
        o_coord << std::setw(w2) << std::setprecision(6) << std::fixed << r;
        o_coord << std::string(w4 - 1, ' ') << ':';
        o_coord << std::setw(w3) << std::setprecision(6) << std::fixed << x;
        o_coord << std::setw(w3) << std::setprecision(6) << std::fixed << y;
        o_coord << std::setw(w3) << std::setprecision(6) << std::fixed << z;
        println(0, o_coord.str());
    }
    mrcpp::print::separator(0, '=', 2);
}
```

2022-04-25 12:39 UTC, Andersmb commented
Where is the appropriate place to print information about SCRF and the cavity? Now I am printing in `driver.cpp` when setting up `ReactionOperator`, since this block only gets executed if a reaction field is requested.

2022-04-25 13:03 UTC, stigrj commented on src/environment/SCRF.cpp
> +void SCRF::printParameters() {
Looks good!

You mean like `print_utils::coord()`? No I think it is fine like this, `coord` is a bit more general and useful to extract.

2022-04-25 13:06 UTC, stigrj commented on src/utils/print_utils.cpp
> +    int w1 = w0 * 2 / 9 - txtBuffer;
:mage_man: :magic_wand:

2022-04-25 13:13 UTC, Andersmb commented on src/environment/SCRF.cpp
> +void SCRF::printParameters() {
Okay, then I'll leave it as it is 👍

2022-04-25 13:27 UTC, stigrj commented
Ok, we need to fix this, there should not be any `cavity_coords` input section in the `molecule` when we don't have any solvent. This needs to be screened out in the Python part.

2022-04-25 13:58 UTC, stigrj commented on src/utils/print_utils.cpp
> +    int w1 = w0 * 2 / 9 - txtBuffer;
Two more nitpicky things on the `json` printer:
1. Each line should start and end with a whitespace
2. I would like the colons on all the different sections in the output to line up (unless you provide a `very very very long` name), so the string length should be minimum `w1`
```
int w0 = Printer::getWidth() - 2;
int w1 = w0 * 2 / 9;
```

2022-04-26 09:30 UTC, Andersmb commented on src/utils/print_utils.cpp
> +    int w1 = w0 * 2 / 9 - txtBuffer;
Okay, the method should adhere to these criteria now :) 

Left- and right-aligned sample sections compared to a `Molecule` section:

```console
===========================================================================
                                 Molecule
---------------------------------------------------------------------------
 Charge                  :                                               1
 Multiplicity            :                                               1
---------------------------------------------------------------------------
    N    Atom            :               x               y               z
---------------------------------------------------------------------------
    0      Li            :        0.000000        0.000000        0.000000
---------------------------------------------------------------------------
 Center of mass          :        0.000000        0.000000        0.000000
===========================================================================


---------------------------------------------------------------------------
 k s sdf                 : 1.0 
 kjsdhf kjsf             : 1.0 
 ks jdfkjs               : 1.0 
---------------------------------------------------------------------------
 k s sdf                 :                                             1.0 
 kjsdhf kjsf             :                                             1.0 
 ks jdfkjs               :                                             1.0 
---------------------------------------------------------------------------
 jd jfdhfj  dhf                     : 1.0 
 jdj f djf hdjhfj dh fjd fjd djfhfj : 1.0 
 jh djfh jdfhjdh fjd fhjdh fjd      : 1.0 
---------------------------------------------------------------------------
 jd jfdhfj  dhf                     :                                  1.0 
 jdj f djf hdjhfj dh fjd fjd djfhfj :                                  1.0 
 jh djfh jdfhjdh fjd fhjdh fjd      :                                  1.0 
---------------------------------------------------------------------------
 jd jfdhfj  dhf                                                              : 1.0 
 jdj f djf hdjhfj dh fjd fjd hdfj dhf jdhf jdhf jdfhjd fhjdhfjdhf jd fdjfhfj : 1.0 
 jh djfh jdfhjdh fjd fhjdh fjd                                               : 1.0 
---------------------------------------------------------------------------
 jd jfdhfj  dhf                                                              : 1.0 
 jdj f djf hdjhfj dh fjd fjd hdfj dhf jdhf jdhf jdfhjd fhjdhfjdhf jd fdjfhfj : 1.0 
 jh djfh jdfhjdh fjd fhjdh fjd                                               : 1.0 
---------------------------------------------------------------------------
```

2022-04-26 09:36 UTC, Andersmb commented
This will interfere a bit with PR #404, since the molecule and cavity validation has been abstracted to its own validator class. How best proceed?

2022-04-26 09:55 UTC, stigrj commented
Yes, I see the JSON printer was also introduced in the other PR, so let's finish that one first. Can you move the final version of the JSON printer over to #404, then I can have a look at the Cavity stuff after lunch. Not sure where to put it yet

2022-04-27 08:36 UTC, stigrj commented
If you first `squash` these into a single commit, then a `rebase` on the new `upstream` will result in only trivial conflicts.

2022-04-27 08:56 UTC, stigrj commented
We should also fix some of the solvent related printouts:
- The reaction potential printout at `print_level > 1` does not fit well with the rest
- I don't like the final reaction energy print
```
===========================================================================
                         Molecular Energy (final)
---------------------------------------------------------------------------
 Kinetic energy          :            (au)                 67.700399048617
 E-N energy              :            (au)               -181.201728318483
 Coulomb energy          :            (au)                 37.493587268261
 Exchange energy         :            (au)                  0.000000000000
 X-C energy              :            (au)                 -7.627268432947
 Ext. field (el)         :            (au)                  0.000000000000
---------------------------------------------------------------------------
 N-N energy              :            (au)                  9.039235444235
 Ext. field (nuc)        :            (au)                  0.000000000000
 Tot. Reac. Energy       :            (au)                 -6.737278530459
 El. Reac. Energy        :            (au)                  5.062225603410
 Nuc. Reac. Energy       :            (au)                -11.799504133868
---------------------------------------------------------------------------
 Electronic energy       :            (au)                -78.572784831142
 Nuclear energy          :            (au)                 -2.760268689633
---------------------------------------------------------------------------
 Total energy            :            (au)             -8.133305352077e+01
                         :      (kcal/mol)             -5.103726163876e+04
                         :        (kJ/mol)             -2.135399026966e+05
                         :            (eV)             -2.213185133919e+03
===========================================================================
```

2022-04-27 09:21 UTC, stigrj commented
Now `printCavity()` can be put in `driver::init_molecule`, after the cavity has been initialized (and move `printGeometry()` _above_ the cavity block).

Not sure where the SCRF output should be though, but these are "parameters" of the calculation and not "program output", so the SCRF print should be enclosed in
```
~~~~~~~

~~~~~~~
```
and not
```
========

========
```
Actually, the "Physical Constants" should perhaps also be `~`

2022-04-28 18:50 UTC, Andersmb commented
> If you first `squash` these into a single commit, then a `rebase` on the new `upstream` will result in only trivial conflicts.

Before I mess everything up: Is this what I should do?

First do a
```console
git rebase -i 8ae9f19d
```
and change `pick` to `squash` for all commits except the top one in the commit file?

And then do a 

```console
git rebase upstream/master
```

and resolve conflicts?

And then a

```console
git push --force
```

?

2022-04-28 18:56 UTC, stigrj commented
Sounds about right, starting with a `git fetch upstream`. Could be a good idea to make a backup branch with the current state in case something :boom: in your face :smile_cat:

2022-04-30 13:11 UTC, Andersmb commented
I'll give it a 10% chance that I did the rebase correctly...

2022-05-01 06:16 UTC, stigrj commented
Looks like the `print_utils::json` got duplicated

2022-05-01 07:05 UTC, Andersmb commented
Is it okay to just fix this "manually" by adding new commits.

2022-05-02 14:04 UTC, Andersmb commented
The physical constants printouts should look like this

```console
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 angstrom2bohrs            :                            1.8897261246257702 
 dipmom_au2debye           :                            2.5417464739297717 
 electron_g_factor         :                             -2.00231930436256 
 fine_structure_constant   :                               0.0072973525693 
 hartree2ev                :                               27.211386245988 
 hartree2kcalmol           :                             627.5094740630558 
 hartree2kjmol             :                            2625.4996394798254 
 hartree2simagnetizability :                                    78.9451185 
 hartree2wavenumbers       :                                219474.6313632 
 light_speed               :                                 137.035999084 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

or with a `headline`
***************************************************************************
***                                                                     ***
***                           Physical Constants                        ***
***                                                                     ***
***************************************************************************

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 angstrom2bohrs            :                            1.8897261246257702 
 dipmom_au2debye           :                            2.5417464739297717 
 electron_g_factor         :                             -2.00231930436256 
 fine_structure_constant   :                               0.0072973525693 
 hartree2ev                :                               27.211386245988 
 hartree2kcalmol           :                             627.5094740630558 
 hartree2kjmol             :                            2625.4996394798254 
 hartree2simagnetizability :                                    78.9451185 
 hartree2wavenumbers       :                                219474.6313632 
 light_speed               :                                 137.035999084 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

2022-05-05 12:01 UTC, stigrj commented
Sorry, I dropped out a bit here :slightly_smiling_face: I think a headline is perhaps a bit excessive?

2022-05-10 11:52 UTC, stigrj commented
We now get many new energy contributions that are printed in the end even if they are not relevant. Same with the upcoming PBC addition. We should be printing only non-zero terms, at least for the non standard contributions.

2022-05-10 12:13 UTC, stigrj commented
I like the new parameter output :+1: I wonder if the dielectric constants rather belong in the cavity part of the output? The problem is, they are not immediately connected in the code. We have the `Cavity` which is a pure geometric thing, which is combined with the dielectric constants into a physical `Permittivity`, which is then used to build the `ReactionPotential` in the `SCRF`.

Perhaps it's the `Permittivity` that should be printed, which would contain a `Cavity`, the dielectric constants and the "formulation" ("exponential" seems to be the only one implemented, but could still be stated in the output). And then we can print this `Permittivity` together with the `SCRF` optimization parameters just after their construction, before we start the ground-state SCF.

2022-05-18 09:45 UTC, Andersmb commented
@stigrj:
> Perhaps it's the `Permittivity` that should be printed, which would contain a `Cavity`, the dielectric constants and the "formulation" ("exponential" seems to be the only one implemented, but could still be stated in the output). And then we can print this `Permittivity` together with the `SCRF` optimization parameters just after their construction, before we start the ground-state SCF (instead of printing the `Cavity` up front together with the molecular geometry).

I have moved the printing to `Permittivity.cpp`. But when printing these just after construction, which would be in `driver::build_fock_operator`, their placement in the output file does not seem optimal to me. For example, the Li test output looks like this:

<details>
<summary>Output file: Parameters printed in `driver::build_fock_operator`</summary>

```
                                                                           
***************************************************************************
***                                                                     ***
***                                                                     ***
***          __  __ ____   ____ _                                       ***
***         |  \/  |  _ \ / ___| |__   ___ _ __ ___                     ***
***         | |\/| | |_) | |   | '_ \ / _ \ '_ ` _ \                    ***
***         | |  | |  _ <| |___| | | |  __/ | | | | |                   ***
***         |_|  |_|_| \_\\____|_| |_|\___|_| |_| |_|                   ***
***                                                                     ***
***         VERSION            1.1.0-alpha                              ***
***                                                                     ***
***         Git branch         solvent-printouts                        ***
***         Git commit hash    fecdbe0524a548a8600b-dirty               ***
***         Git commit author  Anders Brakestad                         ***
***         Git commit date    Tue May 10 10:24:30 2022 +0200           ***
***                                                                     ***
***         Contact: luca.frediani@uit.no                               ***
***                                                                     ***
***         Radovan Bast            Magnar Bjorgve                      ***
***         Roberto Di Remigio      Antoine Durdek                      ***
***         Luca Frediani           Gabriel Gerez                       ***
***         Stig Rune Jensen        Jonas Juselius                      ***
***         Rune Monstad            Peter Wind                          ***
***                                                                     ***
***************************************************************************

---------------------------------------------------------------------------

 MPI processes           :       (no bank)                               1
 OpenMP threads          :                                               1
 Total cores             :                                               1
                                                                           
---------------------------------------------------------------------------

XCFun DFT library Copyright 2009-2020 Ulf Ekstrom and contributors.
See http://dftlibs.org/xcfun/ for more information.

This is free software; see the source code for copying conditions.
There is ABSOLUTELY NO WARRANTY; not even for MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE. For details see the documentation.
Scientific users of this library should cite
U. Ekstrom, L. Visscher, R. Bast, A. J. Thorvaldsen and K. Ruud;
J.Chem.Theor.Comp. 2010, DOI: 10.1021/ct100117s

---------------------------------------------------------------------------

 MRCPP version         : 1.4.0-alpha
 Git branch            : HEAD
 Git commit hash       : 2797a7a18efb69942a6e
 Git commit author     : Stig Rune Jensen
 Git commit date       : Fri Mar 12 12:48:07 2021 +0100

 Linear algebra        : EIGEN v3.3.7
 Parallelization       : NONE

---------------------------------------------------------------------------


                                                                           
===========================================================================
                         MultiResolution Analysis
---------------------------------------------------------------------------
 polynomial order      : 5
 polynomial type       : Interpolating
---------------------------------------------------------------------------
 total boxes           : 8
 boxes                 : [          2           2           2 ]
 unit lengths          : [   16.00000    16.00000    16.00000 ]
 scaling factor        : [    1.00000     1.00000     1.00000 ]
 lower bounds          : [  -16.00000   -16.00000   -16.00000 ]
 upper bounds          : [   16.00000    16.00000    16.00000 ]
 total length          : [   32.00000    32.00000    32.00000 ]
===========================================================================


~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                            Physical Constants
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 angstrom2bohrs            :                            1.8897261246257702 
 dipmom_au2debye           :                            2.5417464739297717 
 electron_g_factor         :                             -2.00231930436256 
 fine_structure_constant   :                               0.0072973525693 
 hartree2ev                :                               27.211386245988 
 hartree2kcalmol           :                             627.5094740630558 
 hartree2kjmol             :                            2625.4996394798254 
 hartree2simagnetizability :                                    78.9451185 
 hartree2wavenumbers       :                                219474.6313632 
 light_speed               :                                 137.035999084 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


                                                                           
***************************************************************************
***                                                                     ***
***                        Initializing Molecule                        ***
***                                                                     ***
***************************************************************************
                                                                           
                                                                           
===========================================================================
                                 Molecule
---------------------------------------------------------------------------
 Charge                  :                                               1
 Multiplicity            :                                               1
---------------------------------------------------------------------------
    N    Atom            :               x               y               z
---------------------------------------------------------------------------
    0      Li            :        0.000000        0.000000        0.000000
---------------------------------------------------------------------------
 Center of mass          :        0.000000        0.000000        0.000000
===========================================================================


                                                                           
***************************************************************************
***                                                                     ***
***                 Computing Ground State Wavefunction                 ***
***                                                                     *** [...]

2022-07-06 07:16 UTC, stigrj commented
Kind of forgot about this. What's the status here? I agree your latter example looks better

2022-07-06 21:45 UTC, stigrj commented
Actually, after looking more closely on this today, I think the correct thing is to print the Permittivity/Cavity information up front, and at the same time include solvent effect in the initial guess energy. This would be more in line with the rest of the terms.

For the initial guess, the orbitals are always "given" by the chosen method (previous `mw` calculation, `sad` guess, `gto` guess, etc), i.e. the solvent is not included (and should not be) when computing these initial orbitals. However, the initial *energy* should be computed with the "correct" electronic method using these given orbitals, i.e. solvent effects should be included here.

@Gabrielgerez why did we disable solvent effects on the `first_iteration` when setting up the `ReactionPotential`? I guess it had to do with some convergence issue with a poor guess density, but I don't see how it would make a difference to postpone the first SCRF from the initial guess and into the first SCF calculation. The first SCRF convergence should be much the same, no?

I will add some of these changes to this branch tomorrow.

2022-07-08 13:09 UTC, stigrj commented
For now the solvent effect is *not* added to the initial energy, but I will make a follow-up PR where I suggest to change this.

Bottom line:
- Cavity information is now printed up front along with the molecular geometry, since this will (soon) have an effect also on the initial energy
- SCRF optimization parameters are not printed until you reach a `print_level` that exposes some details on this part. This now happens at `print_level=3` and looks like this:
```
===========================================================================
                        Building Reaction operator
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 Density type            : total 
 Dynamic threshold       : On 
 KAIN solver             : 5 
 Max iterations          : 100 
 Method                  : SCRF 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 Precision                                  (rel)              1.00000e-05
 Threshold                                  (abs)              4.79355e-02
---------------------------------------------------------------------------
 Vacuum density                   1256 nds        55.88 MB        0.28 sec
 Vacuum potential                  712 nds        31.68 MB        1.43 sec
 Initial gamma                    2312 nds       102.87 MB        0.31 sec
---------------------------------------------------------------------------
 Iter   1 :             1.775248394621e+01    3.457329e+00        1.89 sec
 Iter   2 :             2.656614712073e+01    9.020400e+00        1.86 sec
 Iter   3 :             1.429949183650e+01    1.257527e+01        2.11 sec
 Iter   4 :             1.970794345167e+01    1.718968e+00        1.96 sec
 Iter   5 :             2.174428071669e+01    1.207012e+00        2.10 sec
 Iter   6 :             2.037670045217e+01    8.438552e-01        2.29 sec
 Iter   7 :             2.097124673548e+01    8.051072e-03        2.30 sec
---------------------------------------------------------------------------
 Reaction potential               1400 nds        62.29 MB       14.51 sec
---------------------------------------------------------------------------
                         Wall time: 1.65223e+01 sec
===========================================================================
```

2022-07-08 13:17 UTC, stigrj commented
Also rearranged the molecular energy output to this, with a similar block for external field terms:
```
===========================================================================
                         Molecular Energy (final)
---------------------------------------------------------------------------
 Kinetic energy          :            (au)                 88.754508805409
 E-N energy              :            (au)               -250.283910448742
 Coulomb energy          :            (au)                 62.007501412212
 Exchange energy         :            (au)                  0.000000000000
 X-C energy              :            (au)                -11.030631380367
 N-N energy              :            (au)                 19.012380172434
---------------------------------------------------------------------------
 Reaction energy (el)    :            (au)                  0.792270103652
 Reaction energy (nuc)   :            (au)                 -2.209027911782
 Reaction energy (tot)   :            (au)                 -1.416757808129
---------------------------------------------------------------------------
 Electronic energy       :            (au)               -109.760261507836
 Nuclear energy          :            (au)                 16.803352260652
---------------------------------------------------------------------------
 Total energy            :            (au)             -9.295690924718e+01
                         :      (kcal/mol)             -5.833134123223e+04
                         :        (kJ/mol)             -2.440583317156e+05
                         :            (eV)             -2.529486361758e+03
===========================================================================
```

2022-07-08 14:05 UTC, merged