Add poisson-boltzmann to the SCRF
MRChemSoft/mrchem pull request #450
Opened 2023-04-17 14:19 UTC by Gabrielgerez

Here I have added the alternative to solve the 1:1 Poisson-Boltzmann equation as a part of the SCRF procedure. Right now the parameters are hardcoded but will soon make them user-determined.

2023-10-05 06:27 UTC, robertodr commented on python/template.yml
> +          Parameters for the debye-huckel screening factor
```suggestion
          Parameters for the Debye-Huckel screening factor
```

2023-10-05 06:32 UTC, robertodr commented on src/environment/Cavity.h
> +
these appear to be unused, so you can remove them.
```suggestion
```

2023-10-05 06:32 UTC, robertodr commented on src/environment/Cavity.h
> +    Cavity(){};
I'm not sure why you need this CTOR, I don't think there's ever a situation where the default CTOR is needed.

2023-10-05 06:34 UTC, robertodr commented on src/environment/DHScreening.h
> +    DHScreening(const Cavity cavity_ion, double kappa_out, std::string formulation);
Pass large objects which you're not going to modify by `const` reference https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rf-in
```suggestion
    DHScreening(const Cavity & cavity_ion, double kappa_out, const std::string & formulation);
```

2023-10-06 12:16 UTC, Gabrielgerez commented on src/environment/Cavity.h
> +    Cavity(){};
This was part of early testing and remained until now, thanks for spotting it :)

2023-10-11 09:02 UTC, ilfreddy requested changes

2023-11-10 09:31 UTC, Gabrielgerez commented on src/environment/Cavity.h
> +
They are used by the printer methods in the Permittivity and DHScreening classes

2023-11-14 12:43 UTC, Gabrielgerez commented on src/driver.cpp
I think I am following the convention. Class is first uppercase then camelcase. Member methods are simply camelcase and member variables are `_` separated

2023-11-17 09:57 UTC, Gabrielgerez commented on src/environment/GPESolver.h
I have now added documentation, check that it is acceptable

2023-11-17 13:51 UTC, Gabrielgerez commented on src/qmfunctions/qmfunction_utils.h
> +using mrcpp::ComplexFunctionVector;
Wasnt necessary

2023-11-20 09:03 UTC, Gabrielgerez commented on src/qmfunctions/qmfunction_utils.h
> +using mrcpp::ComplexFunctionVector;
properly removed now

2023-11-20 09:06 UTC, Gabrielgerez commented on src/environment/Cavity.h
> +
Correction, it was the getters that were used. These are removed now

2023-11-20 09:35 UTC, ilfreddy approved these changes

2023-11-23 14:19 UTC, robertodr commented on python/mrchem/api.py
> +    if (user_dict["WaveFunction"]["environment"].lower()).split("_")[0] == "pcm":
wouldn't this work as well?
```suggestion
    if "pcm" in user_dict["WaveFunction"]["environment"].lower():
```

2023-11-24 13:33 UTC, Gabrielgerez commented on python/mrchem/api.py
> +    if (user_dict["WaveFunction"]["environment"].lower()).split("_")[0] == "pcm":
I think I tried something similar, we can add it just to see if it still works

2024-02-06 13:16 UTC, Gabrielgerez commented on python/mrchem/validators.py
> +        if user_dict["WaveFunction"]["environment"].lower().split("_")[0] == "pcm":
Changed it in the newest commit

2024-02-13 11:49 UTC, Gabrielgerez commented on python/mrchem/api.py
> +from .periodictable import PeriodicTableByZ as PT_Z
I think, I did not edit this part of the file as far as I remember

2024-02-14 12:25 UTC, ilfreddy approved these changes

2024-02-14 12:25 UTC, merged