Radii fix
MRChemSoft/mrchem pull request #463
Opened 2023-09-20 14:01 UTC by Gabrielgerez

Finally I implement a simple fix for the default radii for the solvent. This has been an open issue since #419. 
Its not the prettiest fix, but I think it does its job.

2023-09-20 20:43 UTC, stigrj commented
I would really like to avoid introducing `qcelemental` as a runtime dependency.

If I understand the `PhysicalConstants` analogue correctly, `qcelemental` is used only as a dev dependency when updating the input `template.yml` file. Then, in `update_input_parser.py`, the parameters are fetched from `qcelemental` and put as default values in a dedicated `Constants` section in the regular input. Not sure if we want to pass all these radii through the standard input file, though?

How about having `update_input_parser.py` write directly to the `periodictable.py` file?

Any thoughts @robertodr ?

2023-09-20 20:52 UTC, stigrj commented
Actually, perhaps it's not such a bad idea to pass the entire periodic table through the regular input file? In general we would of course fall back to default values, so the regular user would never have to bother with it. But then the advanced user could easily change a single parameter directly in the input file for use in a particular run, without hard coding a change in a static `periodictable.py` file.

2023-09-21 06:31 UTC, robertodr commented
I agree with Stig that we should *not* add Python packages as required production dependencies. They should all stay as development dependencies and the data needed from them should be saved in the `mrchem` Python module, which only needs a working Python interpreter to do its job.

I think it's OK to update `periodictable.py` using `qcelemental` and I think passing it through the parser as done with the constants is a good idea, since it's exposed to the advanced user.

2023-09-21 14:10 UTC, Gabrielgerez commented
I have now added the periodic table to the template through the update_input_parser. There are some issues, for example there are elements for which there are no valid vdw-radii in the mantina set. Another one is that the element `No` is confusing the parser since `no` is a reserved yaml keyword for a boolean false (also the `yes` keyword for true)

2023-09-21 14:42 UTC, Gabrielgerez commented
Tests are failing, have added a lot of the files that are under `python/mrchem/input_parser/plumbing/pyparsing` as it seems there is a bit of version issues. Will most likely revert these changes later

2023-09-25 08:33 UTC, Gabrielgerez commented
Everything should be working now. Have some issues with Nobellium and elements without radius entry in the mantina set, but otherwise it should be ok.

2023-09-25 08:47 UTC, robertodr commented on python/mrchem/update_input_parser.py
>  import argparse
Did you run this file through the Black formatter?

2023-09-25 08:49 UTC, robertodr commented on python/mrchem/update_input_parser.py
> +            radius = 1.2*aa2bohr
Why convert to atomic units here? The `periodictable.py` is human-readable, so I think we should keep things in Angstrom.

2023-09-25 08:50 UTC, Gabrielgerez commented on python/mrchem/update_input_parser.py
> +            radius = 1.2*aa2bohr
well, all the radii are in atomic units already, so I would be converting one way or the other. I can do it the other way around if it is better

2023-09-25 08:51 UTC, robertodr commented on python/mrchem/update_input_parser.py
> +                radius = vals[0]
I think you can set `radius = None` when there is not available radius in the table. You can check on `None` in the parser helper for the solvent and throw an error at that point.

2023-09-25 08:52 UTC, robertodr commented on python/mrchem/validators.py
> +
less lines of code
```suggestion
            radii = [self.user_dict["Elements"][x.lower()]["vdw-radius"] for x in self.atomic_symbols]
```

2023-09-25 08:54 UTC, robertodr requested changes
I think you need to run Black and isort on `periodictable.py` and `validators.py`

2023-09-25 08:58 UTC, Gabrielgerez commented on python/mrchem/update_input_parser.py
> +                radius = vals[0]
I was trying this, but I just cannot get the typing for the yaml entry right. Do you know what we are using for `NoneType` there?

2023-09-25 08:58 UTC, Gabrielgerez commented on python/mrchem/update_input_parser.py
>  import argparse
no

2023-09-25 08:59 UTC, robertodr commented on python/mrchem/update_input_parser.py
> +            radius = 1.2*aa2bohr
When dumping the YAML, I'd leave them in Angstrom.

2023-09-25 09:07 UTC, robertodr commented on python/mrchem/update_input_parser.py
> +                radius = vals[0]
Checked and it's not possible, because we never implemented `Union` types (such as `Optional[float]`) in the parser. So the check can be done by using a sentinel value instead, _e.g._ `-1`.

2023-09-25 11:39 UTC, Gabrielgerez commented on python/mrchem/update_input_parser.py
> +                radius = vals[0]
Ok, I'll set it to -1.0 for now then.

2023-09-25 12:39 UTC, Gabrielgerez commented
> I think you need to run Black and isort on `periodictable.py` and `validators.py`

Do we have a special configuration file for this? I ran `isort --profile black` on both files, but it barely changed anything

2023-09-25 12:42 UTC, Gabrielgerez commented on python/mrchem/update_input_parser.py
> +            radius = 1.2*aa2bohr
Using angstrom for everything now

2023-09-25 12:43 UTC, Gabrielgerez commented on python/mrchem/update_input_parser.py
>  import argparse
now it is, but barely any change

2023-09-26 06:25 UTC, robertodr commented
So for formatting it's:
`black <files-to-format>`
and for sorting the imports it's:
`isort <files-to-sort>`

2023-09-26 06:27 UTC, robertodr commented on python/mrchem/update_input_parser.py
> +        if ele.lower() == "h":
Adding a comment as to why we patch the value for Hydrogen might be useful for who reads this code in the future.
```suggestion
        if ele.lower() == "h":
           # these vdw radii are used with a continuum solvation model and 1.2 AA for hydrogen is more appropriate than the default
```

2023-09-26 06:28 UTC, robertodr commented on python/mrchem/validators.py
> +                    "The vdw-radius of element {x} is not defined in the mantina set".format(x)
f-strings should be preferred:
```suggestion
                    f"The vdw-radius of element {x} is not defined in the mantina set"
```

2023-09-26 06:29 UTC, robertodr approved these changes
Two more small comments, but otherwise looks good!

2023-09-26 07:20 UTC, Gabrielgerez commented
> Two more small comments, but otherwise looks good!

Alright, i have now added all suggestions :)
We can finally fix this bug

2023-09-26 12:18 UTC, merged