Linear response with solvent
MRChemSoft/mrchem pull request #471
Opened 2023-11-10 11:39 UTC by robertodr

Rehash of #456

2023-11-20 09:16 UTC, Gabrielgerez commented on doc/users/user_ref.rst
> +       :outside: Parameters for the continuum solvent outside the cavity.
Not very fond of the naming `outside` maybe we can call it `continuum` or `dielectric_continuum`.

2023-11-20 15:53 UTC, robertodr commented on doc/users/user_ref.rst
> +       :outside: Parameters for the continuum solvent outside the cavity.
good idea.

2023-11-22 11:32 UTC, Gabrielgerez commented on python/mrchem/input_parser/docs/user_ref.rst
> +       :outside: Parameters for the continuum solvent outside the cavity.
Same comment as above, we should use something more memorable

2023-11-22 11:32 UTC, Gabrielgerez commented on python/template.yml
> +          - name: outside
Naming here as well

2023-11-22 12:57 UTC, Gabrielgerez requested changes
I left some questions and comments. I really like how the `ReactionPotential` looks now. I mentioned the naming of the `outside` section, but it is not that essential besides aesthetics.

2023-11-22 12:57 UTC, Gabrielgerez commented on src/driver.cpp
> +            if (order == 1 && noneq && is_dynamic) {
why do we need both `is_dynamic` and `noneq` it seems that both are needed for the response solvent.

2023-11-22 12:57 UTC, Gabrielgerez commented on src/environment/SCRF.h
>      auto computeEnergies(const Density &rho_el) -> std::tuple<double, double>;
Since you use `std::tie` as the return statement in `FockBuilder`, should we also just write this as 
```suggestion
    auto computeEnergies(const Density &rho_el) -> std::tie<double, double>;
```
to keep it clear what we are working with?

2023-11-22 13:22 UTC, robertodr commented on src/driver.cpp
> +            if (order == 1 && noneq && is_dynamic) {
you can decide to use the equilibrium formulation even when $\omega \neq 0$

2023-11-22 13:23 UTC, robertodr commented on src/environment/SCRF.h
>      auto computeEnergies(const Density &rho_el) -> std::tuple<double, double>;
No, `tie` is to bind elements of a tuple to existing variables: it's a function not a data container. https://en.cppreference.com/w/cpp/utility/tuple/tie

2023-11-24 11:42 UTC, Gabrielgerez commented on src/environment/SCRF.h
>      auto computeEnergies(const Density &rho_el) -> std::tuple<double, double>;
alright

2023-11-24 11:48 UTC, Gabrielgerez reviewed
I like the new naming of the `outside` section of the input. besides the comment on the `.gitignore` everything looks good to me

2023-11-24 11:48 UTC, Gabrielgerez commented on .gitignore
> +tests/**/*.out
Is this something we want to keep for the master branch?

2023-11-24 12:14 UTC, robertodr commented on .gitignore
> +tests/**/*.out
Perhaps not. I've only added the JSON under `reference` for the new tests though. That's what counts anyway.

2023-11-24 12:51 UTC, merged